version: '3.1'

services:
    test:
        image: test
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - "/app:/app"